# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('lschet', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('addressSTR', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('planstruct', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('flat', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('person', models.IntegerField()),
                ('space', models.FloatField(default=0)),
            ],
        ),
    ]
