# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('params', models.TextField()),
                ('compress', models.BooleanField()),
                ('debug', models.BooleanField()),
                ('json', models.BooleanField()),
                ('isdead', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('isresponsed', models.BooleanField(default=False)),
                ('inprogress', models.BooleanField(default=False)),
                ('deadrequested', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('resp', models.TextField()),
                ('method', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('isresponsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
