# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-10 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImpersonalRNG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='request',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
